// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZd2X84BrMoLHdpuRbpB36pxjwUFh6n6o',
    appId: '1:1090082208257:web:17a28c2d394dc79114de00',
    messagingSenderId: '1090082208257',
    projectId: 'blackcoffer-a38e2',
    authDomain: 'blackcoffer-a38e2.firebaseapp.com',
    storageBucket: 'blackcoffer-a38e2.appspot.com',
    measurementId: 'G-H59J8QBXV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnWACjZsVgaVVCzluO_pybfWTDI2_eAdE',
    appId: '1:1090082208257:android:91fd70f73f58fd0914de00',
    messagingSenderId: '1090082208257',
    projectId: 'blackcoffer-a38e2',
    storageBucket: 'blackcoffer-a38e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvob81LR48XyY1CN0GP5r_j_66TlA7TW0',
    appId: '1:1090082208257:ios:2c0742207f5e399914de00',
    messagingSenderId: '1090082208257',
    projectId: 'blackcoffer-a38e2',
    storageBucket: 'blackcoffer-a38e2.appspot.com',
    iosBundleId: 'com.example.blackcoffer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvob81LR48XyY1CN0GP5r_j_66TlA7TW0',
    appId: '1:1090082208257:ios:e9beede30b5eca1714de00',
    messagingSenderId: '1090082208257',
    projectId: 'blackcoffer-a38e2',
    storageBucket: 'blackcoffer-a38e2.appspot.com',
    iosBundleId: 'com.example.blackcoffer.RunnerTests',
  );
}
